### ISSUE TITLE
writeAccReg(regAddr reg, byte value) Initialization Error

### ISSUE THREAD

**Issue by mjs513** [pololu/lsm303-arduino#11]
I  installed the latest lsm303 lib through the Arduino Lib manager and am receiving a Initialization error on writing to the acc register.   Here is the complete error:

> ..........\Arduino\libraries\LSM303\LSM303.cpp: At global scope:

> .......\Arduino\libraries\LSM303\LSM303.cpp:259:6: error: prototype for 'void LSM303::writeAccReg(byte, byte)' does not match any in class 'LSM303'
> 
>  void LSM303::writeAccReg(byte reg, byte value)
>       ^
> In file included from C:\Users\CyberPalin\Documents\Arduino\libraries\LSM303\LSM303.cpp:1:0:
> 
> .......\Arduino\libraries\LSM303/LSM303.h:177:10: error: candidate is: void LSM303::writeAccReg(LSM303::regAddr, byte)
> 
>      void writeAccReg(regAddr reg, byte value);
>           ^
> 
> .....\Arduino\libraries\LSM303\LSM303.cpp: In member function 'void LSM303::writeReg(byte, byte)':
> 
> C:\Users\CyberPalin\Documents\Arduino\libraries\LSM303\LSM303.cpp:321:27: error: invalid conversion from 'byte {aka unsigned char}' to 'LSM303::regAddr' [-fpermissive]
> 
>      writeAccReg(reg, value);
>                            ^
> 
> In file included from.......\Arduino\libraries\LSM303\LSM303.cpp:1:0:
> 
> ......\Arduino\libraries\LSM303/LSM303.h:177:10: error:   initializing argument 1 of 'void LSM303::writeAccReg(LSM303::regAddr, byte)' [-fpermissive]
> 
>      void writeAccReg(regAddr reg, byte value);

Not sure what the issue is.

thanks for your help
Mike

**Comment by kevin-pololu** [comment]
Hi, Mike.

What version of the Arduino IDE are you using, and what board are you trying to compile for? Are you using one of the example sketches or did you write your own? Could you confirm that you installed version 3.0.1 of the LSM303 library?

Kevin

**Comment by mjs513** [comment]
Hi Kevin

I am running IDE 1.6.10 and tried compiling it for both the Mega and Teensy 3.5.  I first used it for my custom sketch and then tried it with the Heading example.  I checked the library.properties file and it stated it was version 3.0.1.

Just for reference the old version worked with no problem. 

Thanks
Mike

**Comment by kevin-pololu** [comment]
What was the old version that you were using? If you installed it manually a long time ago, it might have had a different directory structure and left some files that are conflicting with the latest library. (Some of your errors seem to indicate a pretty old version of the library.) You might want to try deleting the library entirely from your Arduino\libraries folder and then reinstalling it from the Library Manager to see if that helps.

If you keep having trouble, could you also try updating your Arduino software to the latest version, 1.6.13? I haven't been able to reproduce your problem so far with that version.

Kevin

**Comment by mjs513** [comment]
Hi Kevin.

Yes it was a pretty old version and I did install it manually. Deleting the lsm303 directory completely and reinstalling seemed to do the trick.  Everything compiles fine.  Now I know what to do if I run into the problem again which I probably will ::)

Thanks for your help.  Have a great holidaty
Mike
