### ISSUE TITLE
Does anyone have any idea how to set up the click interrupts?

### ISSUE THREAD

**Issue by tcannon79** [pololu/lsm303-arduino#12]
I am having a hell of a time with that.

**Comment by Arrowana** [comment]
The documentation gives 2 registers related to the click detection:

- CLICK_CFG_A -> Axis to enable for click detection -> Start with ZS to 1 (single click)
- CLICK_SRC_A -> Enabling click/double-click interrupt, sign of the threshold
- CLICK_THS_A -> Acceleration threshold to detect a click event
- TIME_LIMIT_A -> Time limit to disregard click if acceleration is prolonged in time
- TIME_LATENCY_A -> Ignore repeated event during time latency for single click  
- TIME_WINDOW_A -> Ignore repeated event during time window for double click

Then use CTRL_REG3_A to enable click interrupts by setting I1_CLICK to 1

Set the registers according to what you need and you should get click interrupts.

I will probably implement the feature shortly
