### ISSUE TITLE
LSM303DLHC heading calculation issue

### ISSUE THREAD

**Issue by Soulskater** [pololu/lsm303-arduino#9]
Hi,

I'm ported this example, in node js(the readings coming from executed python code),
so the pitch and roll calculations are ok, but the heading is a bit weird for me. I set the from vector to (0, -1, 0) as the example said, so in this case the heading should show the angle between the North and the y axis.Correct me if i'm wrong but when i testing, i keep the board paralell to the ground and rotate it.It seems the 0 is in the right direction, but when i'm rotate the board the angle is not correct.
Mainly my heading calculations in this file:
https://github.com/Soulskater/RobotControl/blob/master/services/compass/compassService.js
The raw data comes from this python files:
https://github.com/Soulskater/RobotControl/blob/master/python/Magnetometer.py
https://github.com/Soulskater/RobotControl/blob/master/python/Accelerometer.py

Do you have any idea?
Thanks,
Gabor

**Comment by DavidEGrayson** [comment]
I am closing this because it does not appear to be an issue with our LSM303 library.  If you post on our [forum](http://forum.pololu.com), there might be someone interested in helping you debug your program.
